from __future__ import annotations

from typing import Protocol

from .domain import (
    Project,
    ProjectDeploymentAccess,
    ProjectKnowledgeSource,
    ProjectPipelineBinding,
    ProjectWorkspace,
)


class ProjectWorkspaceProvisioner(Protocol):
    def provision(self, repository_ref: str) -> str: ...
    def reset(self, repository_ref: str) -> str: ...


class ProjectRepository(Protocol):
    def create(self, project: Project, workspace: ProjectWorkspace) -> None: ...
    def get(self, project_id: str) -> Project | None: ...
    def list(self) -> tuple[Project, ...]: ...
    def get_workspace(self, project_id: str) -> ProjectWorkspace | None: ...
    def update_project(self, project: Project, expected_version: int) -> None: ...
    def update_workspace(self, workspace: ProjectWorkspace) -> None: ...
    def acquire_lease(self, project_id: str, delivery_id: str) -> None: ...
    def release_lease(self, project_id: str, delivery_id: str) -> None: ...
    def active_delivery_id(self, project_id: str) -> str | None: ...
    def list_pipeline_bindings(self, project_id: str) -> tuple[ProjectPipelineBinding, ...]: ...
    def put_pipeline_binding(
        self, binding: ProjectPipelineBinding, expected_version: int | None
    ) -> None: ...
    def list_deployment_access(self, project_id: str) -> tuple[ProjectDeploymentAccess, ...]: ...
    def put_deployment_access(
        self, access: ProjectDeploymentAccess, expected_version: int | None
    ) -> None: ...
    def list_knowledge_sources(self, project_id: str) -> tuple[ProjectKnowledgeSource, ...]: ...
    def put_knowledge_source(
        self, source: ProjectKnowledgeSource, expected_version: int | None
    ) -> None: ...
