from __future__ import annotations

from typing import Protocol

from .domain import (
    Project,
    ProjectAccessAudit,
    ProjectDeploymentAccess,
    ProjectKnowledgeSource,
    ProjectKnowledgeSourceApproval,
    ProjectMembership,
    ProjectPipelineBinding,
    ProjectWorkspace,
)
from .domain import (
    ProjectRepository as ProjectRepositoryRecord,
)


class ProjectWorkspaceProvisioner(Protocol):
    def provision(self, repository_ref: str) -> str: ...
    def reset(self, repository_ref: str) -> str: ...
    def revision(self, repository_ref: str) -> str: ...


class ProjectTeamGovernance(Protocol):
    def validate_team_revision(self, revision_id: str) -> None: ...
    def bind_project(self, project_id: str, revision_id: str) -> object: ...
    def has_binding(self, project_id: str) -> bool: ...


class ProjectRepository(Protocol):
    def create(
        self,
        project: Project,
        workspace: ProjectWorkspace,
        *,
        legacy_repository: bool = True,
    ) -> None: ...
    def get(self, project_id: str) -> Project | None: ...
    def list(self) -> tuple[Project, ...]: ...
    def get_workspace(self, project_id: str) -> ProjectWorkspace | None: ...
    def update_project(self, project: Project, expected_version: int) -> None: ...
    def update_workspace(self, workspace: ProjectWorkspace) -> None: ...
    def list_repositories(self, project_id: str) -> tuple[ProjectRepositoryRecord, ...]: ...
    def put_repository(self, repository: ProjectRepositoryRecord) -> None: ...
    def acquire_lease(self, project_id: str, delivery_id: str) -> None: ...
    def release_lease(self, project_id: str, delivery_id: str) -> None: ...
    def active_delivery_id(self, project_id: str) -> str | None: ...
    def list_pipeline_bindings(self, project_id: str) -> tuple[ProjectPipelineBinding, ...]: ...
    def put_pipeline_binding(
        self, binding: ProjectPipelineBinding, expected_version: int | None
    ) -> None: ...
    def list_deployment_access(self, project_id: str) -> tuple[ProjectDeploymentAccess, ...]: ...
    def put_deployment_access(
        self, access: ProjectDeploymentAccess, expected_version: int | None
    ) -> None: ...
    def list_knowledge_sources(self, project_id: str) -> tuple[ProjectKnowledgeSource, ...]: ...
    def put_knowledge_source(
        self, source: ProjectKnowledgeSource, expected_version: int | None
    ) -> None: ...
    def list_knowledge_source_approvals(
        self, project_id: str
    ) -> tuple[ProjectKnowledgeSourceApproval, ...]: ...
    def list_all_knowledge_source_approvals(
        self,
    ) -> tuple[ProjectKnowledgeSourceApproval, ...]: ...
    def put_knowledge_source_approval(
        self,
        approval: ProjectKnowledgeSourceApproval,
        expected_version: int | None,
    ) -> None: ...
    def list_memberships(self, project_id: str) -> tuple[ProjectMembership, ...]: ...
    def get_membership(self, project_id: str, user_id: str) -> ProjectMembership | None: ...
    def list_membership_project_ids(self, user_id: str) -> tuple[str, ...]: ...
    def get_authorization_version(self, project_id: str) -> int: ...
    def put_membership(
        self, membership: ProjectMembership, expected_version: int | None
    ) -> None: ...
    def delete_membership(self, project_id: str, user_id: str, expected_version: int) -> None: ...
    def append_access_audit(self, audit: ProjectAccessAudit) -> None: ...
    def list_access_audits(self, project_id: str) -> tuple[ProjectAccessAudit, ...]: ...
